let addItemBtn = document.getElementById('add-item-btn')
let form = document.getElementById('section__form')
let taskInput = document.getElementById('task-input')
let deadlineInput = document.getElementById('deadline-input')
let stateInput = document.getElementById('state-input')
let cancelBtn = document.getElementById('cancel-btn')
let confirmBtn = document.getElementById('confirm-btn')
let itemsContainer = document.getElementById('items-container')